package com.criterya.orco.model;

// Generated 07-sep-2015 0:05:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private static final long serialVersionUID = 4096281699864178785L;
	private Integer idlog;
	private Date fecha;
	private String texto;

	public Log() {
	}

	public Log(Date fecha) {
		this.fecha = fecha;
	}

	public Log(Date fecha, String texto) {
		this.fecha = fecha;
		this.texto = texto;
	}

	public Integer getIdlog() {
		return this.idlog;
	}

	public void setIdlog(Integer idlog) {
		this.idlog = idlog;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

}
