package com.criterya.orco.model;

// Generated 07-sep-2015 0:05:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Pickup generated by hbm2java
 */
public class Pickup implements java.io.Serializable {

	private static final long serialVersionUID = 8997693386640834938L;
	private Integer id;
	private Integer frame;
	private Date currentTime;
	private Integer countBlobs;
	private Integer blobId;
	private Integer blobX;
	private Integer blobY;
	private Integer blobDepth;
	private Integer blobHandId;
	private Integer blobHandX;
	private Integer blobHandY;
	private Integer blobHandDepth;
	private String newTablecol;

	public Pickup() {
	}

	public Pickup(Integer frame, Date currentTime, Integer countBlobs,
			Integer blobId, Integer blobX, Integer blobY, Integer blobDepth,
			Integer blobHandId, Integer blobHandX, Integer blobHandY,
			Integer blobHandDepth, String newTablecol) {
		this.frame = frame;
		this.currentTime = currentTime;
		this.countBlobs = countBlobs;
		this.blobId = blobId;
		this.blobX = blobX;
		this.blobY = blobY;
		this.blobDepth = blobDepth;
		this.blobHandId = blobHandId;
		this.blobHandX = blobHandX;
		this.blobHandY = blobHandY;
		this.blobHandDepth = blobHandDepth;
		this.newTablecol = newTablecol;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFrame() {
		return this.frame;
	}

	public void setFrame(Integer frame) {
		this.frame = frame;
	}

	public Date getCurrentTime() {
		return this.currentTime;
	}

	public void setCurrentTime(Date currentTime) {
		this.currentTime = currentTime;
	}

	public Integer getCountBlobs() {
		return this.countBlobs;
	}

	public void setCountBlobs(Integer countBlobs) {
		this.countBlobs = countBlobs;
	}

	public Integer getBlobId() {
		return this.blobId;
	}

	public void setBlobId(Integer blobId) {
		this.blobId = blobId;
	}

	public Integer getBlobX() {
		return this.blobX;
	}

	public void setBlobX(Integer blobX) {
		this.blobX = blobX;
	}

	public Integer getBlobY() {
		return this.blobY;
	}

	public void setBlobY(Integer blobY) {
		this.blobY = blobY;
	}

	public Integer getBlobDepth() {
		return this.blobDepth;
	}

	public void setBlobDepth(Integer blobDepth) {
		this.blobDepth = blobDepth;
	}

	public Integer getBlobHandId() {
		return this.blobHandId;
	}

	public void setBlobHandId(Integer blobHandId) {
		this.blobHandId = blobHandId;
	}

	public Integer getBlobHandX() {
		return this.blobHandX;
	}

	public void setBlobHandX(Integer blobHandX) {
		this.blobHandX = blobHandX;
	}

	public Integer getBlobHandY() {
		return this.blobHandY;
	}

	public void setBlobHandY(Integer blobHandY) {
		this.blobHandY = blobHandY;
	}

	public Integer getBlobHandDepth() {
		return this.blobHandDepth;
	}

	public void setBlobHandDepth(Integer blobHandDepth) {
		this.blobHandDepth = blobHandDepth;
	}

	public String getNewTablecol() {
		return this.newTablecol;
	}

	public void setNewTablecol(String newTablecol) {
		this.newTablecol = newTablecol;
	}

}
