package com.criterya.orco.model;

// Generated 07-sep-2015 0:05:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Times generated by hbm2java
 */
public class Times implements java.io.Serializable {

	private static final long serialVersionUID = -2221812814703750905L;
	private Integer id;
	private int weekDay;
	private Date start;
	private Date finish;
	private Boolean saveVideoRGB;
	private Boolean saveVideoDEPTH;

	public Times() {
	}

	public Times(int weekDay, Date start, Date finish) {
		this.weekDay = weekDay;
		this.start = start;
		this.finish = finish;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getWeekDay() {
		return this.weekDay;
	}

	public void setWeekDay(int weekDay) {
		this.weekDay = weekDay;
	}

	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public Date getFinish() {
		return this.finish;
	}

	public void setFinish(Date finish) {
		this.finish = finish;
	}

	public Boolean getSaveVideoRGB() {
		return saveVideoRGB;
	}

	public void setSaveVideoRGB(Boolean saveVideoRGB) {
		this.saveVideoRGB = saveVideoRGB;
	}

	public Boolean getSaveVideoDEPTH() {
		return saveVideoDEPTH;
	}

	public void setSaveVideoDEPTH(Boolean saveVideoDEPTH) {
		this.saveVideoDEPTH = saveVideoDEPTH;
	}

}
